version: '3'

services:
  mysql:
    container_name: maskbox-mysql
    restart: unless-stopped
    image: mysql:8.0.30
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql-data: {}
